openapi: 3.0.0
servers: []
info:
  description: This is the API of the AEGIS Harvester component
  version: "0.1"
  title: AEGIS Harvester API
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /repositories:
    get:
      tags:
        - Repositories
      responses:
        '200':
          description: list all repositories
    post:
      tags:
        - Repositories
      responses:
        '200':
          description: list all repositories
  /annotations:
    get:
      tags:
        - Annotations
      responses:
        '200':
          description: list all annotations
    post:
      tags:
        - Annotations
      responses:
        '200':
          description: list all annotations
  /harvesters:
    get:
      tags:
        - Harvesters
      responses:
        '200':
          description: list all harvesters
    post:
      tags:
        - Harvesters
      responses:
        '200':
          description: list all harvesters
  /runs:
    get:
      tags:
        - Runs
      responses:
        '200':
          description: list all runs
    post:
      tags:
        - Runs
      responses:
        '200':
          description: list all runs